author:
    name: Jason Cemra
    github: https://github.com/CemraJC/

markdown: kramdown

version: 0.7

urls:
    plover: "http://stenoknight.com/wiki/Getting_Started#Installing_Plover"
    laser-keytoppers: "http://plover.deco-craft.com/shop/view_product/Laser-Cut-Steno-Keys-Kit"
    ergonomics: "http://plover.stenoknight.com/2010/05/ergonomic-argument.html"
    shapeways: "http://www.shapeways.com/"
    github-page: "https://github.com/cemrajc/stenotoppers"
    fdm-printing:
    shapeways-upload:

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      developers: Jason Cemra
      status: Prerelease