author:
    name: Jason Cemra
    github: https://github.com/CemraJC/

markdown: kramdown

version: 1.0

urls:
    plover: "http://stenoknight.com/wiki/Getting_Started#Installing_Plover"
    laser-keytoppers: "http://plover.deco-craft.com/shop/view_product/Laser-Cut-Steno-Keys-Kit"
    ergonomics: "http://plover.stenoknight.com/2010/05/ergonomic-argument.html"
    shapeways: "http://www.shapeways.com/"
    github-page: "https://github.com/cemrajc/stenotoppers"
    fdm-printing: "https://en.wikipedia.org/wiki/Fused_deposition_modeling"
    shapeways-upload: "https://www.shapeways.com/shops/logical-store?section=Stenography+and+Plover&s=0"
    fitting-guide: "https://github.com/CemraJC/stenotoppers/blob/master/FITTING-GUIDE.md"

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      developers: Jason Cemra
      status: Prerelease